{
  "lang.name": "English", 
  "lang.region": "United Kingdom", 
  "sel.yes": "Yes", 
  "sel.no": "No", 
  "sets.downloadRenderDistance": "Version List Length", 
  "sets.resolutionWidth": "Width of the game window", 
  "sets.resolutionHeight": "Height of the game window", 
  "sets.startupPage": "The startup page", 
  "sets.info": "About", 
  "sets.info.value": "%1, by HlHill",
  "mod.fabric": "Fabric", 
  "mod.forge": "Forge",  
  "mod.optifine": "OptiFine", 
  "mod.prompt": "Install %1? ", 
  "mod.optifineWithForge": "%1, compatible with %2", 
  "title.main": "River Launcher", 
  "title.modify": "Install %1", 
  "title.launch": "Launch", 
  "title.downloads": "Downloads", 
  "title.accounts": "Accounts", 
  "title.settings": "Settings", 
  "title.language": "Language", 
  "title.log": "Minecraft Log", 
  "do.launch": "Launch Game", 
  "do.language": "Switch Language", 
  "do.accounts": "Switch Account", 
  "do.accounts.new": "Create New Account", 
  "downloads.latest": "Latest version: %1", 
  "downloads.latests": "Latest release: %1; Latest snapshot: %2",
  "downloads.goto": "Go to (Nothing for the latest version) ", 
  "downloads.unable": "Unable to find version \"%1\". ", 
  "downloads.another": "Did you mean %1? ",  
  "downloads.prompt": "Download version \"%1\"? ", 
  "downloads.custom": "Custom name (Nothing for origin name) ", 
  "downloads.downloading": "%1 downloading...", 
  "downloads.finish": "Finish downloading %1! ", 
  "downloads.assets": "Assets", 
  "downloads.libraries": "Libraries", 
  "downloads.client": "Client", 
  "downloads.logging": "Logging File",
  "downloads.type.release": "Release    ", 
  "downloads.type.snapshot": "Snapshot   ", 
  "downloads.type.old_beta": "Old Beta   ", 
  "downloads.type.old_alpha": "Old Alpha  ", 
  "downloads.date": "%1.%2.%3 %4:%5:%6", 
  "launch.instead": "Download an instance instead! ", 
  "launch.remove": "Remove",
  "launch.removePrompt": "Remove the selected instance? ",
  "launch.directory": "Open Directory",  
  "launch.account": "Create an accounts instead! ", 
  "launch.rename": "Rename", 
  "launch.renamePrompt": "Rename the selected instance: ",
  "launch.end": "Game stopped! ", 
  "settings.static": "Static value! ", 
  "settings.edit": "Edit \"%1\" ", 
  "settings.type": "Please input %1! ", 
  "settings.type.int": "numbers", 
  "settings.type.int": "pages", 
  "accounts.instead": "Create an account instead! ", 
  "accounts.type.mojang": "Official", 
  "accounts.type.legacy": "Offline", 
  "accounts.info": "User type: %1", 
  "accounts.type": "User type ", 
  "accounts.prompt": "Opening the login website in your browser, copy the address into the entry below after the login finish. ", 
  "accounts.name": "User name ",
  "accounts.remove": "Remove", 
  "accounts.removePrompt": "Remove the selected account? ",
  "accounts.current": "Current account: %1", 
  "main.update": "Updated from %1 to %2! \nUpdate log: ", 
  "main.new": "New version released: %1! ", 
  "main.dialog": "Dialog", 
  "main.warn": "Warning", 
  "main.warnContent": "Do not give the file \".river_cfg.json\" to anyone! This file contains your private information! ", 
  "update.build.1": ("Fixed bugs", ), 
  "update.build.2": ("Fixed legacy versions' ${user_properties} bug", ), 
  "update.build.3": ("Added Help", ), 
  "update.build.4": ("Could now remove versions and accounts",
                   "Modified update log showing"), 
  "update.build.5": ("Could now open location directories of instances",
                   "Would now downloads logging xml file",
                   "Modified update log showing"), 
  "update.build.6": ("Would now ask to install Fabric",
                   "Could now see the info of Minecraft",
                   "Modified update log showing",
                   "Fixed legacy versions' ${auth_session} bug",
                   "Would now check Minecraft's sha1 hash value"), 
  "update.build.7": ("Now support multi-language",
                   "Would now ask to install Optifime"), 
  "update.build.8": ("Would now ask to install Forge",
                   "Could now rename instances", 
                   "Now support multi-language update log"), 
  "update.build.9": ("Fixed bugs", 
                   "Would now open \".minecraft\\versions\" folder when pressing \"f\" in page \"Launch\" while no instances there"),
  "update.build.10": ("Added GUI", )
}
