{
  "lang.name": "中文", 
  "lang.region": "中国",
  "sel.yes": "是", 
  "sel.no": "否", 
  "sets.downloadRenderDistance": "版本列表长度", 
  "sets.resolutionWidth": "游戏窗口宽度", 
  "sets.resolutionHeight": "游戏窗口高度",
  "sets.startupPage": "开始页", 
  "sets.info": "关于启动器", 
  "sets.info.value": "%1, HlHill做的",
  "mod.fabric": "Fabric", 
  "mod.forge": "Forge",  
  "mod.optifine": "高清修复",
  "mod.prompt": "安装%1吗? ", 
  "mod.optifineWithForge": "%1, 与%2兼容", 
  "title.main": "河流启动器", 
  "title.modify": "安装%1", 
  "title.downloads": "下载", 
  "title.launch": "启动", 
  "title.accounts": "账户", 
  "title.settings": "设置", 
  "title.language": "语言", 
  "title.log": "Minecraft日志", 
  "do.launch": "启动游戏", 
  "do.language": "更改语言", 
  "do.accounts.new": "创建新账户", 
  "do.accounts": "更改账户", 
  "downloads.latest": "最新的版本: %1", 
  "downloads.latests": "最新的正式版: %1; 最新的快照: %2",
  "downloads.goto": "跳转到 (留空表示最新版本) ", 
  "downloads.unable": "无法找到版本 \"%1\". ", 
  "downloads.another": "你是说 %1 吗? ",  
  "downloads.prompt": "下载版本 \"%1\" 吗? ", 
  "downloads.custom": "自定义名称 (留空表示默认名称) ", 
  "downloads.downloading": "正在下载%1...", 
  "downloads.finish": "%1下载完成! ", 
  "downloads.assets": "资源", 
  "downloads.libraries": "依赖库", 
  "downloads.client": "客户端", 
  "downloads.logging": "日志文件", 
  "downloads.type.release": "正式版        ", 
  "downloads.type.snapshot": "快照          ", 
  "downloads.type.old_beta": "远古Beta版    ", 
  "downloads.type.old_alpha": "远古Alpha版   ", 
  "downloads.date": "%1年%2月%3日 %4:%5:%6", 
  "launch.instead": "先下载一个版本! ", 
  "launch.remove": "移除",
  "launch.removePrompt": "移除所选版本? ",
  "launch.directory": "打开目录",  
  "launch.account": "先创建一个账户! ", 
  "launch.rename": "重命名", 
  "launch.renamePrompt": "重命名所选版本: ",
  "launch.end": "游戏已停止! ", 
  "settings.static": "不可改变! ", 
  "settings.edit": "编辑 \"%1\" ", 
  "settings.type": "请输入%1! ", 
  "settings.type.int": "数字", 
  "accounts.instead": "先创建一个账户! ", 
  "accounts.type.mojang": "正版", 
  "accounts.type.legacy": "离线", 
  "accounts.info": "用户类型: %1", 
  "accounts.type": "用户类型 %1", 
  "accounts.prompt": "正在你的浏览器打开登陆页面, 登录结束后将地址复制到下面的输入框内. ", 
  "accounts.name": "用户名称 ", 
  "accounts.remove": "移除", 
  "accounts.removePrompt": "移除所选账户? ", 
  "accounts.current": "当前账户: %1", 
  "main.update": "从%1更新到了%2! \n更新日志: ", 
  "main.new": "新版本发布了: %1! ",
  "main.dialog": "对话框", 
  "main.warn": "警告", 
  "main.warnContent": "不要把文件\".river_cfg.json\"给任何人! 这个文件包含你的私密信息! ", 
  "update.build.1": ("修复了一些漏洞", ), 
  "update.build.2": ("修复了旧版本的${user_properties}漏洞", ), 
  "update.build.3": ("增加了帮助", ), 
  "update.build.4": ("现在可以移除版本和账户了",
                   "更改了更新日志的显示"), 
  "update.build.5": ("现在可以打开版本所在的目录了",
                   "现在会下载日志文件了",
                   "更改了更新日志的显示"), 
  "update.build.6": ("现在会询问是否下载Fabric了",
                   "想在可以看到Minecraft的信息了",
                   "更改了更新日志的显示",
                   "修复了旧版本的${auth_session}漏洞",
                   "现在会检查Minecraft的sha1哈希值"), 
  "update.build.7": ("支持多语言了",
                   "现在会询问是否下载高清修复"), 
  "update.build.8": ("现在会询问是否下载Forge",
                   "现在可以重命名版本了", 
                   "现在支持多语言的更新日志了"), 
  "update.build.9": ("修复了漏洞", 
                   "现在, 当在\"启动\"界面按\"f\"时, 如果没有版本的话, 会打开\".minecraft\\versions\"文件夹"),
  "update.build.10": ("增加了GUI", )

}
